# Generated by Django 6.0.2 on 2026-02-24 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('votes_count', models.PositiveIntegerField(default=0)),
                ('voters', models.ManyToManyField(blank=True, related_name='voted_project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
