# Generated by Django 6.0.2 on 2026-03-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_verified_account_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('student', 'Student'), ('others', 'others')], max_length=20),
        ),
    ]
